# Configs for SiT training
# Path settings
data_dir: "/private/home/mingyangd/imagenet"
checkpoints_dir: "/private/home/mingyangd/dmy/nn_flow/checkpoints"
output_dir: "/private/home/mingyangd/dmy/output_nn_flow"
fid_stats:
  imagenet32: "/private/home/mingyangd/dmy/nn_flow/utils/fid_stats/adm_in32_stats.npz"
  imagenet256: "/private/home/mingyangd/dmy/nn_flow/utils/fid_stats/adm_in256_stats.npz"

# W&B settings for logging
wandb:
  project: "sit-test"
  entity: "mit-hair"
  name: null

# Distributed training settings
# dist_url: "env://" # this doesn't work for slurm

# Dataset configuration
dataset:
  name: "imagenet64"
  test_batch_size: 128
  img_shape: [3, 64, 64]

# Model architecture
model:
  data_shape: [3, 64, 64]
  mu: -1.2
  sigma: 1.2
  sit_type: "SiT-S/4"
  depth: 8
  patch_size: 4
  num_heads: 6
  hidden_size: 384
  noise_classes: 0


# Training parameters
train:
  n_steps: 200000
  total_batch_size: 1024
  ema_dict:
    halflife_kimg: 20
  save_per_step: 10000
  eval_gen_per_step: 1000
  compile_model: false
  use_bf16: true
  lr_schedule:
    lr: 0.0001
    warmup_kimg: 4000
    total_kimg: 2000000
    clip_grad: 1.0
  drop_class: 0.1
  load_dict:
    run_id: ""
    epoch: ""
    continue_training: false

# Optimizer settings
optimizer:
  lr: 0.0001
  weight_decay: 0.01