# Configuration for biased_mixtures toy dataset (imbalanced mixture components)
gen:
  type: "mlp"
  kwargs:
    noise_dim: 64
    output_dim: 2
    acti: "relu"

dataset: 
  name: "edm_toy"

train:
  n_steps: 10000
  data_bsz: 2
  gen_per_data: 128
  pos_per_data: 128
  lr_schedule:
    lr: 0.003
    clip_grad: 1.0
  loss_config:
    type: "attn_new"
    R_list: [0.02, 0.05, 0.1, 0.2]

wandb:
  name: "edm_toy_sanity"
  project: "toy_kernel"
  entity: "mit-hair"
